# Importing Libraries

In [18]:
import pandas as pd
import sys
import os

In [19]:
project_path = os.path.abspath(os.path.join(os.getcwd(), ".."))
if project_path not in sys.path:
    sys.path.append(project_path)

import utils.get_data_utils as gdu

# Data indicators and filters metadata

In [20]:
# Get the list of years for analysis
time_period = [ str(t) for t in range(2010, 2024)]

# Get the list of countries for analysis
country_codes = [
    "BE",  # Belgium
    #"EL",  # Greece - not included due to lack of data
    "LT",  # Lithuania
    "PT",  # Portugal
    "BG",  # Bulgaria
    "ES",  # Spain
    "LU",  # Luxembourg
    "RO",  # Romania
    "CZ",  # Czechia
    "FR",  # France
    "HU",  # Hungary
    "SI",  # Slovenia
    "DK",  # Denmark
    "HR",  # Croatia
    "MT",  # Malta
    "SK",  # Slovakia
    "DE",  # Germany
    "IT",  # Italy
    "NL",  # Netherlands
    "FI",  # Finland
    "EE",  # Estonia
    "CY",  # Cyprus
    "AT",  # Austria
    "SE",  # Sweden
    "IE",  # Ireland
    "LV",  # Latvia
    "PL"   # Poland
]


# Get the list of indicators along with their filters for our analysis
indicators = {
    'prc_hpi_a': { # House price index
        "unit": "RCH_A_AVG", # Annual average rate of change
        "purchase": "TOTAL",
        "label": "house_price_index"
    },  
    'tipsho60': { # Standardised house price-to-income ratio
        "unit": "PTIR_LT_AVG", # Price-to-income ratio relative to long-term average
        "label": "price_income_ratio"
    }, 
    'sts_cobp_a': { # Building permits
        "unit": "PCH_SM", # Index, 2021=100
        "indic_bt": "BPRM_SQM", # Building permits - m2 of useful floor area
        "cpa2_1": "CPA_F41001", # Residential buildings
        "label": "building_permits"
    }, 
    'sts_copi_a': { # Construction producer prices or costs, new residential buildings
        "unit": "PCH_SM", # Percentage change compared to same period in previous year
        "indic_bt": "PRC_PRR", # Producer prices
        "label": "construction_prices"
    }, 
    'tps00003': { # Population density
        "label": "pop_density"
    }, 
    'prc_hicp_midx': { # HICP - inflation rate
        "unit": "I15",
        "coicop": "CP00",
        "freq": "M",
        "label": "inflation_rate"
    }, 
    'tps00019': { # Population change - crude rates of total change, natural change and net migration plus adjustment
        "indic_de": "GROWRT", # Crude rate of total population change
        "label": "pop_change"
    }, 
    'tesem120': { # Unemployment rate by sex
        "sex": "T",
        "label": "unemployment_rate"
    },
    "nama_10_pc": { # GDP per capita
        "unit": "CP_EUR_HAB",
        "na_item": "B1GQ",
        "label": "gdp_per_capita"
    }
}


for indicator in indicators:
    indicators[indicator]['geo'] = country_codes
    indicators[indicator]['time'] = time_period
    if 'freq' not in indicators[indicator]:
        indicators[indicator]['freq'] = 'A'

print(indicators)

{'prc_hpi_a': {'unit': 'RCH_A_AVG', 'purchase': 'TOTAL', 'label': 'house_price_index', 'geo': ['BE', 'LT', 'PT', 'BG', 'ES', 'LU', 'RO', 'CZ', 'FR', 'HU', 'SI', 'DK', 'HR', 'MT', 'SK', 'DE', 'IT', 'NL', 'FI', 'EE', 'CY', 'AT', 'SE', 'IE', 'LV', 'PL'], 'time': ['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'], 'freq': 'A'}, 'tipsho60': {'unit': 'PTIR_LT_AVG', 'label': 'price_income_ratio', 'geo': ['BE', 'LT', 'PT', 'BG', 'ES', 'LU', 'RO', 'CZ', 'FR', 'HU', 'SI', 'DK', 'HR', 'MT', 'SK', 'DE', 'IT', 'NL', 'FI', 'EE', 'CY', 'AT', 'SE', 'IE', 'LV', 'PL'], 'time': ['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'], 'freq': 'A'}, 'sts_cobp_a': {'unit': 'PCH_SM', 'indic_bt': 'BPRM_SQM', 'cpa2_1': 'CPA_F41001', 'label': 'building_permits', 'geo': ['BE', 'LT', 'PT', 'BG', 'ES', 'LU', 'RO', 'CZ', 'FR', 'HU', 'SI', 'DK', 'HR', 'MT', 'SK', 'DE', 'IT', 'NL', 'FI', 'EE', 'CY', 'AT', 'SE', 'IE', 'LV', 'PL'], 'time': ['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'], 'freq': 'A'}, 'sts_copi_a': {'unit': 'PCH_SM', 'indic_bt': 'PRC_PRR', 'label': 'construction_prices', 'geo': ['BE', 'LT', 'PT', 'BG', 'ES', 'LU', 'RO', 'CZ', 'FR', 'HU', 'SI', 'DK', 'HR', 'MT', 'SK', 'DE', 'IT', 'NL', 'FI', 'EE', 'CY', 'AT', 'SE', 'IE', 'LV', 'PL'], 'time': ['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'], 'freq': 'A'}, 'tps00003': {'label': 'pop_density', 'geo': ['BE', 'LT', 'PT', 'BG', 'ES', 'LU', 'RO', 'CZ', 'FR', 'HU', 'SI', 'DK', 'HR', 'MT', 'SK', 'DE', 'IT', 'NL', 'FI', 'EE', 'CY', 'AT', 'SE', 'IE', 'LV', 'PL'], 'time': ['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'], 'freq': 'A'}, 'prc_hicp_midx': {'unit': 'I15', 'coicop': 'CP00', 'freq': 'M', 'label': 'inflation_rate', 'geo': ['BE', 'LT', 'PT', 'BG', 'ES', 'LU', 'RO', 'CZ', 'FR', 'HU', 'SI', 'DK', 'HR', 'MT', 'SK', 'DE', 'IT', 'NL', 'FI', 'EE', 'CY', 'AT', 'SE', 'IE', 'LV', 'PL'], 'time': ['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023']}, 'tps00019': {'indic_de': 'GROWRT', 'label': 'pop_change', 'geo': ['BE', 'LT', 'PT', 'BG', 'ES', 'LU', 'RO', 'CZ', 'FR', 'HU', 'SI', 'DK', 'HR', 'MT', 'SK', 'DE', 'IT', 'NL', 'FI', 'EE', 'CY', 'AT', 'SE', 'IE', 'LV', 'PL'], 'time': ['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'], 'freq': 'A'}, 'tesem120': {'sex': 'T', 'label': 'unemployment_rate', 'geo': ['BE', 'LT', 'PT', 'BG', 'ES', 'LU', 'RO', 'CZ', 'FR', 'HU', 'SI', 'DK', 'HR', 'MT', 'SK', 'DE', 'IT', 'NL', 'FI', 'EE', 'CY', 'AT', 'SE', 'IE', 'LV', 'PL'], 'time': ['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'], 'freq': 'A'}, 'nama_10_pc': {'unit': 'CP_EUR_HAB', 'na_item': 'B1GQ', 'label': 'gdp_per_capita', 'geo': ['BE', 'LT', 'PT', 'BG', 'ES', 'LU', 'RO', 'CZ', 'FR', 'HU', 'SI', 'DK', 'HR', 'MT', 'SK', 'DE', 'IT', 'NL', 'FI', 'EE', 'CY', 'AT', 'SE', 'IE', 'LV', 'PL'], 'time': ['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'], 'freq': 'A'}}

# Downloading and saving raw data

In [21]:
df = gdu.get_eurostat_data(indicators)
print("Data retrieved from Eurostat")

Data retrieved from Eurostat

In [22]:
df.to_csv("../data/raw/01_eu_analysis_data.csv", index=False)
print("Data saved to data/eu_analysis_data.csv")

Data saved to data/eu_analysis_data.csv

# Data Cleaning

In [23]:
df.head()

indicator,geo,time,building_permits,construction_prices,gdp_per_capita,house_price_index,inflation_rate,pop_change,pop_density,price_income_ratio,unemployment_rate
0,AT,2010,7.4,1.7,35170.0,NaN,90.144167,NaN,NaN,86.18,5.2
1,AT,2011,13.0,2.9,36740.0,5.4,93.345000,NaN,101.8,89.63,4.9
2,AT,2012,-10.4,2.6,37570.0,6.6,95.745833,5.2,102.3,91.83,5.2
3,AT,2013,8.6,2.4,37890.0,5.0,97.773333,6.6,102.9,96.93,5.7
4,AT,2014,1.7,2.3,38640.0,3.8,99.201667,9.0,103.7,98.82,6.0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 364 entries, 0 to 363
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   geo                  364 non-null    object
 1   time                 364 non-null    object
 2   building_permits     364 non-null    float64
 3   construction_prices  364 non-null    float64
 4   gdp_per_capita       364 non-null    float64
 5   house_price_index    361 non-null    float64
 6   inflation_rate       364 non-null    float64
 7   pop_change           312 non-null    float64
 8   pop_density          312 non-null    float64
 9   price_income_ratio   364 non-null    float64
 10  unemployment_rate    364 non-null    float64
dtypes: float64(9), object(2)
memory usage: 31.4+ KB

In [25]:
df.isnull().sum()

indicator
geo                     0
time                    0
building_permits        0
construction_prices     0
gdp_per_capita          0
house_price_index       3
inflation_rate          0
pop_change             52
pop_density            52
price_income_ratio      0
unemployment_rate       0
dtype: int64

In [26]:
for column in df.columns:
    print("null values percentage for ", column,": ", df[column].isnull().sum()/df.shape[0]*100)

null values percentage for  geo :  0.0
null values percentage for  time :  0.0
null values percentage for  building_permits :  0.0
null values percentage for  construction_prices :  0.0
null values percentage for  gdp_per_capita :  0.0
null values percentage for  house_price_index :  0.8241758241758242
null values percentage for  inflation_rate :  0.0
null values percentage for  pop_change :  14.285714285714285
null values percentage for  pop_density :  14.285714285714285
null values percentage for  price_income_ratio :  0.0
null values percentage for  unemployment_rate :  0.0

In [27]:
print("Statistics before null values cleaning")
df.describe()

Statistics before null values cleaning

indicator,building_permits,construction_prices,gdp_per_capita,house_price_index,inflation_rate,pop_change,pop_density,price_income_ratio,unemployment_rate
count,364.000000,364.000000,364.000000,361.000000,364.000000,312.000000,312.000000,364.000000,364.000000
mean,1.676374,3.465659,30222.115385,3.908033,104.695250,3.155128,180.541987,97.626099,8.107692
std,20.826308,5.245295,20700.321478,5.952653,10.740783,9.400327,283.144375,13.422513,3.953071
min,-52.700000,-7.400000,5080.000000,-17.100000,87.725833,-23.600000,17.700000,58.250000,2.000000
25%,-11.350000,0.800000,15260.000000,0.300000,99.335417,-2.125000,69.225000,89.645000,5.600000
50%,1.900000,2.300000,24435.000000,4.200000,100.902500,2.700000,105.650000,96.780000,7.200000
75%,14.250000,4.525000,39665.000000,7.200000,106.970833,6.625000,138.200000,104.532500,9.625000
max,138.700000,54.800000,118770.000000,22.300000,160.593333,43.400000,1692.700000,154.030000,26.100000

In [28]:
numeric_columns = [c for c in df.columns if c not in ["geo", "time"]]
for col in numeric_columns:
    df[col] = df.groupby("geo")[col].transform(lambda x: x.fillna(x.mean()))

In [29]:
print("Statistics before null values cleaning")
df.describe()

Statistics before null values cleaning

indicator,building_permits,construction_prices,gdp_per_capita,house_price_index,inflation_rate,pop_change,pop_density,price_income_ratio,unemployment_rate
count,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000
mean,1.676374,3.465659,30222.115385,3.902430,104.695250,3.155128,180.541987,97.626099,8.107692
std,20.826308,5.245295,20700.321478,5.933817,10.740783,9.181644,282.920164,13.422513,3.953071
min,-52.700000,-7.400000,5080.000000,-17.100000,87.725833,-23.600000,17.700000,58.250000,2.000000
25%,-11.350000,0.800000,15260.000000,0.300000,99.335417,-2.225000,69.825000,89.645000,5.600000
50%,1.900000,2.300000,24435.000000,4.200000,100.902500,2.800000,105.650000,96.780000,7.200000
75%,14.250000,4.525000,39665.000000,7.200000,106.970833,6.600000,138.200000,104.532500,9.625000
max,138.700000,54.800000,118770.000000,22.300000,160.593333,43.400000,1692.700000,154.030000,26.100000

In [30]:
df.to_csv("../data/processed/01_cleaned_eu_analysis_data.csv", index=False)
print("Cleaned data saved to data/proccesed/eu_analysis_data.csv")

Cleaned data saved to data/proccesed/eu_analysis_data.csv